# Generated by Django 3.2.17 on 2023-02-05 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=64)),
                ('level', models.IntegerField()),
                ('sentence', models.TextField(max_length=512)),
            ],
        ),
    ]
