# Generated by Django 3.2.17 on 2023-03-06 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mistake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=64)),
                ('issue', models.TextField(max_length=1023)),
                ('author', models.CharField(max_length=255)),
            ],
        ),
    ]
