# Generated by Django 3.2.17 on 2023-03-16 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_mistake'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='conjugation',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='regular',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
