# Generated by Django 3.2.17 on 2023-03-21 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20230315_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
            ],
        ),
    ]
